import { Request, Response } from "express";
import { Types } from "mongoose";
import { Product } from "../models/product.model";
import { cloudinaryUtil } from "../utils/cloudinary.utils";

/* ═══════════════════════════════════════════
   TYPES (match your Product model)
═══════════════════════════════════════════ */

type SellMode = "packaged" | "loose";
type BaseUnit = "mg" | "ml" | "pcs";
type PriceUnit = "kg" | "liter" | "pcs";
type ProductType = "animal" | "food" | "accessory" | "medicine" | "other";

type ImageDto = { url: string; public_id: string };

export interface ParsedVariant {
  _id?: string;

  // sku will be GENERATED by backend (ignored from client)
  sku?: string;

  sellMode: SellMode;

  attributes?: Record<string, string>;

  price: { buying: number; selling: number };
  priceUnit: PriceUnit;

  quantity: { inStock: number; baseUnit: BaseUnit };

  images?: ImageDto[];
  isActive?: boolean;
}

function getExistingVariantFiles(variantId: string, files: Express.Multer.File[]) {
  return files.filter((f) => f.fieldname === `variantImages[${variantId}]`);
}

function removeImagesFromList(existing: ImageDto[], removePublicIds: string[]) {
  const set = new Set(removePublicIds);
  return existing.filter((img) => !set.has(img.public_id));
}

async function deleteImagesByPublicIds(publicIds: string[]) {
  for (const pid of publicIds) {
    await cloudinaryUtil.deleteImage(pid);
  }
}

function safeJsonParse<T>(value: any, fallback: T): T {
  if (value == null) return fallback;
  if (typeof value === "string") {
    const s = value.trim();
    if (!s) return fallback;
    try {
      return JSON.parse(s) as T;
    } catch {
      return fallback;
    }
  }
  // already an object/array
  return value as T;
}


function normalizeStr(v: any) {
  return String(v ?? "").trim();
}

/* ═══════════════════════════════════════════
   SKU GENERATION (backend-only)
   - unique across ALL variants (unique index on variants.sku)
═══════════════════════════════════════════ */

function skuPrefixFromName(name: string) {
  const cleaned = normalizeStr(name).toUpperCase().replace(/[^A-Z0-9]+/g, "");
  // take first 6 chars to keep it short
  return (cleaned.slice(0, 6) || "PRD").padEnd(3, "X");
}

function hashPartFromAttributes(attrs: Record<string, string> | undefined) {
  if (!attrs) return "NA";
  const entries = Object.entries(attrs)
    .map(([k, v]) => `${k}:${v}`)
    .sort()
    .join("|")
    .toUpperCase()
    .replace(/[^A-Z0-9|:]+/g, "");
  // tiny deterministic-ish hash
  let h = 0;
  for (let i = 0; i < entries.length; i++) {
    h = (h * 31 + entries.charCodeAt(i)) >>> 0;
  }
  return (h.toString(36).toUpperCase().slice(0, 4) || "NA").padEnd(2, "A");
}

function randomPart(len = 5) {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no confusing chars
  let out = "";
  for (let i = 0; i < len; i++) out += chars[Math.floor(Math.random() * chars.length)];
  return out;
}

async function generateUniqueSku(productName: string, attrs?: Record<string, string>) {
  const prefix = skuPrefixFromName(productName);
  const attrHash = hashPartFromAttributes(attrs);

  // try a few times; collision chance is tiny, but we still guard
  for (let attempt = 0; attempt < 20; attempt++) {
    const sku = `${prefix}-${attrHash}-${randomPart(5)}`.toUpperCase();
    const exists = await Product.exists({ "variants.sku": sku });
    if (!exists) return sku;
  }

  // last resort (very unlikely)
  const fallbackSku = `${prefix}-${attrHash}-${Date.now().toString(36).toUpperCase()}`.toUpperCase();
  return fallbackSku;
}

/* ═══════════════════════════════════════════
   VALIDATION HELPERS (aligned with model)
═══════════════════════════════════════════ */

function validateVariant(v: ParsedVariant, index: number) {
  const idx = index + 1;

  if (!v.sellMode || !["packaged", "loose"].includes(v.sellMode)) {
    return `Variant ${idx}: sellMode must be 'packaged' or 'loose'`;
  }

  if (!v.price || typeof v.price.buying !== "number" || typeof v.price.selling !== "number") {
    return `Variant ${idx}: price (buying & selling) is required`;
  }
  if (v.price.buying < 0 || v.price.selling < 0) {
    return `Variant ${idx}: price buying/selling must be >= 0`;
  }

  if (!v.priceUnit || !["kg", "liter", "pcs"].includes(v.priceUnit)) {
    return `Variant ${idx}: priceUnit must be 'kg', 'liter', or 'pcs'`;
  }

  if (!v.quantity || typeof v.quantity.inStock !== "number") {
    return `Variant ${idx}: quantity.inStock is required`;
  }
  if (v.quantity.inStock < 0) {
    return `Variant ${idx}: quantity.inStock must be >= 0`;
  }

  if (!v.quantity.baseUnit || !["mg", "ml", "pcs"].includes(v.quantity.baseUnit)) {
    return `Variant ${idx}: quantity.baseUnit must be 'mg', 'ml', or 'pcs'`;
  }

  // ✅ business rules (based on your model intent)
  if (v.sellMode === "packaged") {
    if (v.quantity.baseUnit !== "pcs") {
      return `Variant ${idx}: packaged variants must use baseUnit 'pcs'`;
    }
    if (v.priceUnit !== "pcs") {
      return `Variant ${idx}: packaged variants must use priceUnit 'pcs'`;
    }
  }

  if (v.sellMode === "loose") {
    if (!["mg", "ml"].includes(v.quantity.baseUnit)) {
      return `Variant ${idx}: loose variants must use baseUnit 'mg' or 'ml'`;
    }
    if (
      (v.quantity.baseUnit === "mg" && v.priceUnit !== "kg") ||
      (v.quantity.baseUnit === "ml" && v.priceUnit !== "liter")
    ) {
      return `Variant ${idx}: loose mg must use priceUnit 'kg', loose ml must use priceUnit 'liter'`;
    }
  }

  return null;
}

function sanitizeVariant(v: ParsedVariant) {
  const out: ParsedVariant = {
    _id: v._id,
    sellMode: v.sellMode,
    attributes: v.attributes ?? {},
    price: v.price,
    priceUnit: v.priceUnit,
    quantity: {
      inStock: Number(v.quantity?.inStock ?? 0),
      baseUnit: v.quantity?.baseUnit as BaseUnit,
    },
    images: Array.isArray(v.images) ? v.images : [],
    isActive: v.isActive ?? true,
  };

  // sku is backend-only, do NOT trust client
  delete (out as any).sku;

  return out;
}

/* ═══════════════════════════════════════════
   IMAGE HANDLER
═══════════════════════════════════════════ */

async function handleVariantImages(
  variantIndex: number,
  files: Express.Multer.File[],
  oldImages?: ImageDto[]
) {
  const variantFiles = files.filter(
    (file) => file.fieldname === `variants[${variantIndex}][images]`
  );

  if (variantFiles.length === 0) return null;

  // delete old images if we are replacing
  if (oldImages?.length) {
    for (const img of oldImages) {
      await cloudinaryUtil.deleteImage(img.public_id);
    }
  }

  return cloudinaryUtil.uploadMultiple(variantFiles, "max_pets/images");
}

/* ═══════════════════════════════════════════
   CONTROLLER
═══════════════════════════════════════════ */

export const productController = {
  /* ─────────────────────────────
     CREATE PRODUCT
  ───────────────────────────── */
  async create(req: Request, res: Response) {
    try {
      const name = normalizeStr(req.body.name);
      const category = normalizeStr(req.body.category);
      const type = normalizeStr(req.body.type) as ProductType;

      if (!name) {
        return res.status(400).json({ success: false, message: "name is required" });
      }
      if (!Types.ObjectId.isValid(category)) {
        return res.status(400).json({ success: false, message: "Invalid category id" });
      }
      if (!["animal", "food", "accessory", "medicine", "other"].includes(type)) {
        return res.status(400).json({ success: false, message: "Invalid product type" });
      }

      const description = req.body.description ?? null;

      const specifications = safeJsonParse<Record<string, string>>(req.body.specifications, {});
      const variantOptions = safeJsonParse<any[]>(req.body.variantOptions, []);
      const incomingVariants = safeJsonParse<ParsedVariant[]>(req.body.variants, []);

      if (!Array.isArray(incomingVariants) || incomingVariants.length === 0) {
        return res.status(400).json({
          success: false,
          message: "Product must have at least one variant",
        });
      }

      // validate + sanitize
      const sanitizedVariants: ParsedVariant[] = [];
      for (let i = 0; i < incomingVariants.length; i++) {
        const err = validateVariant(incomingVariants[i], i);
        if (err) return res.status(400).json({ success: false, message: err });
        sanitizedVariants.push(sanitizeVariant(incomingVariants[i]));
      }

      // upload images if multipart
      const files = Array.isArray(req.files) ? (req.files as Express.Multer.File[]) : [];
      if (files.length) {
        for (let i = 0; i < sanitizedVariants.length; i++) {
          const uploaded = await handleVariantImages(i, files);
          if (uploaded) sanitizedVariants[i].images = uploaded;
        }
      }

      // ✅ generate sku for each variant (backend-only)
      const finalVariants = [];
      for (let i = 0; i < sanitizedVariants.length; i++) {
        const v = sanitizedVariants[i];
        const sku = await generateUniqueSku(name, v.attributes);
        finalVariants.push({ ...v, sku });
      }

      const product = await Product.create({
        name,
        category: new Types.ObjectId(category),
        type,
        description,
        specifications,
        variantOptions,
        variants: finalVariants,
      });

      const populated = await Product.findById(product._id).populate("category");
      return res.status(201).json({ success: true, data: populated });
    } catch (error: any) {
      return res.status(500).json({ success: false, message: error.message });
    }
  },

  /* ─────────────────────────────
     UPDATE PRODUCT
  ───────────────────────────── */
  async update(req: Request, res: Response) {
    try {
      const id = normalizeStr(req.params.id);
      if (!Types.ObjectId.isValid(id)) {
        return res.status(400).json({ success: false, message: "Invalid product id" });
      }

      const existingProduct = await Product.findById(id);
      if (!existingProduct) {
        return res.status(404).json({ success: false, message: "Product not found" });
      }

      const name = req.body.name != null ? normalizeStr(req.body.name) : existingProduct.name;
      const category = req.body.category != null ? normalizeStr(req.body.category) : null;
      const type = req.body.type != null ? (normalizeStr(req.body.type) as ProductType) : null;

      if (category && !Types.ObjectId.isValid(category)) {
        return res.status(400).json({ success: false, message: "Invalid category id" });
      }
      if (type && !["animal", "food", "accessory", "medicine", "other"].includes(type)) {
        return res.status(400).json({ success: false, message: "Invalid product type" });
      }

      const description = req.body.description ?? existingProduct.description ?? null;

      const specifications = safeJsonParse<Record<string, string>>(
        req.body.specifications,
        (existingProduct.specifications as any) ?? {}
      );
      const variantOptions = safeJsonParse<any[]>(
        req.body.variantOptions,
        (existingProduct.variantOptions as any) ?? []
      );

      const incomingVariants = safeJsonParse<ParsedVariant[]>(
        req.body.variants,
        (existingProduct.variants as any) ?? []
      );

      if (!Array.isArray(incomingVariants) || incomingVariants.length === 0) {
        return res.status(400).json({
          success: false,
          message: "Product must have at least one variant",
        });
      }

      /**
       * removeVariantImages (optional)
       * client sends JSON string like:
       * {
       *   "<variantId1>": ["public_id1", "public_id2"],
       *   "<variantId2>": ["public_id3"]
       * }
       */
      const removeVariantImages = safeJsonParse<Record<string, string[]>>(
        req.body.removeVariantImages,
        {}
      );

      // validate + sanitize (ignore client sku)
      const sanitizedVariants: ParsedVariant[] = [];
      for (let i = 0; i < incomingVariants.length; i++) {
        const err = validateVariant(incomingVariants[i], i);
        if (err) return res.status(400).json({ success: false, message: err });
        sanitizedVariants.push(sanitizeVariant(incomingVariants[i]));
      }

      const files = Array.isArray(req.files) ? (req.files as Express.Multer.File[]) : [];

      // helpers (keep inside method if you don’t want to move to top)
      const getExistingVariantFiles = (variantId: string) =>
        files.filter((f) => f.fieldname === `variantImages[${variantId}]`);

      const removeImagesFromList = (existing: ImageDto[], removePublicIds: string[]) => {
        const set = new Set(removePublicIds);
        return (existing || []).filter((img) => !set.has(img.public_id));
      };

      const deleteImagesByPublicIds = async (publicIds: string[]) => {
        for (const pid of publicIds) {
          await cloudinaryUtil.deleteImage(pid);
        }
      };

      /**
       * INAL VARIANTS BUILD
       * - Existing variant:
       *   - remove only requested images
       *   - append newly uploaded images (field: variantImages[<variantId>])
       *   - preserve sku
       *
       * - New variant:
       *   - generate sku
       *   - images come from incoming.images (or you can add separate new-variant file fields later)
       */
      const finalVariants: any[] = [];

      for (const incoming of sanitizedVariants) {
        const isExisting = !!incoming._id && Types.ObjectId.isValid(String(incoming._id));

        if (isExisting) {
          const variantId = String(incoming._id);

          const existingVariant: any = existingProduct.variants.find(
            (v: any) => String(v._id) === variantId
          );

          if (!existingVariant) {
            return res.status(400).json({
              success: false,
              message: `Variant not found in product: ${variantId}`,
            });
          }

          // 1) remove requested images
          const removePublicIds = removeVariantImages[variantId] || [];
          if (removePublicIds.length) {
            await deleteImagesByPublicIds(removePublicIds);
          }

          const keptImages: ImageDto[] = removePublicIds.length
            ? removeImagesFromList((existingVariant.images || []) as ImageDto[], removePublicIds)
            : ((existingVariant.images || []) as ImageDto[]);

          // 2) upload new images for this variant (append)
          const newFiles = getExistingVariantFiles(variantId);
          const uploaded: ImageDto[] = newFiles.length
            ? await cloudinaryUtil.uploadMultiple(newFiles, "max_pets/images")
            : [];

          const mergedImages = [...keptImages, ...uploaded];

          // 3) preserve sku
          finalVariants.push({
            ...incoming,
            sku: existingVariant.sku,
            images: mergedImages,
          });
        } else {
          // NEW VARIANT in update
          const sku = await generateUniqueSku(name, incoming.attributes);

          finalVariants.push({
            ...incoming,
            sku,
            images: incoming.images ?? [],
          });
        }
      }

      const updated = await Product.findByIdAndUpdate(
        id,
        {
          name,
          ...(category ? { category: new Types.ObjectId(category) } : {}),
          ...(type ? { type } : {}),
          description,
          specifications,
          variantOptions,
          variants: finalVariants,
        },
        { new: true, runValidators: true }
      ).populate("category");

      return res.json({ success: true, data: updated });
    } catch (error: any) {
      if (error?.code === 11000) {
        return res.status(409).json({
          success: false,
          message: "Duplicate key error (likely SKU collision). Please retry.",
          error: error?.keyValue,
        });
      }
      return res.status(500).json({ success: false, message: error.message });
    }
  },

  /* ─────────────────────────────
     GET ONE
  ───────────────────────────── */
  async getOne(req: Request, res: Response) {
    try {
      const id = normalizeStr(req.params.id);
      if (!Types.ObjectId.isValid(id)) {
        return res.status(400).json({ success: false, message: "Invalid product id" });
      }

      const product = await Product.findById(id).populate("category");
      if (!product || !product.isActive) {
        return res.status(404).json({ success: false, message: "Product not found" });
      }

      return res.json({ success: true, data: product });
    } catch (error: any) {
      return res.status(500).json({ success: false, message: error.message });
    }
  },

  /* ─────────────────────────────
     GET ALL (pagination + filters)
  ───────────────────────────── */
  async getAll(req: Request, res: Response) {
    try {
      const page = Math.max(1, Number(req.query.page || 1));
      const limit = Math.min(200, Math.max(1, Number(req.query.limit || 10)));
      const skip = (page - 1) * limit;

      const search = typeof req.query.search === "string" ? req.query.search.trim() : "";
      const category = typeof req.query.category === "string" ? req.query.category.trim() : "";
      const type = typeof req.query.type === "string" ? req.query.type.trim() : "";
      const isActive =
        req.query.isActive == null ? true : String(req.query.isActive) === "true";

      const query: any = { isActive };

      if (search) query.$text = { $search: search };
      if (category) {
        if (!Types.ObjectId.isValid(category)) {
          return res.status(400).json({ success: false, message: "Invalid category id" });
        }
        query.category = new Types.ObjectId(category);
      }
      if (type) query.type = type;

      const [products, total] = await Promise.all([
        Product.find(query)
          .populate("category")
          .skip(skip)
          .limit(limit)
          .sort({ createdAt: -1 }),
        Product.countDocuments(query),
      ]);

      return res.json({
        success: true,
        data: products,
        pagination: {
          total,
          page,
          limit,
          totalPages: Math.ceil(total / limit),
        },
      });
    } catch (error: any) {
      return res.status(500).json({ success: false, message: error.message });
    }
  },

  /* ─────────────────────────────
     SOFT DELETE
  ───────────────────────────── */
  async delete(req: Request, res: Response) {
    try {
      const id = normalizeStr(req.params.id);
      if (!Types.ObjectId.isValid(id)) {
        return res.status(400).json({ success: false, message: "Invalid product id" });
      }

      const updated = await Product.findByIdAndUpdate(
        id,
        { isActive: false },
        { new: true }
      );

      if (!updated) {
        return res.status(404).json({ success: false, message: "Product not found" });
      }

      return res.json({ success: true, message: "Product soft deleted" });
    } catch (error: any) {
      return res.status(500).json({ success: false, message: error.message });
    }
  },
};